### ISSUE TITLE
Clubs Service

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Club-Manager#15]
## Info

The models have already been implemented, and the REST API just uses the default view and serializer logic. However, when other parts of the app need to manage clubs/members, they should be able to use easy to under stand interfaces/methods. 

The service has already been laid out in `app/clubs/services.py`, with the method names and short docstrings already added in. This task mainly just involves using the models already created to perform the actions described by the doc strings and the method names.

## Task

- [x] get_registration_link
  - Return link to sign up page with query string `?club={club_name}`, this will need to be set up in the urls file
- [x] register_member
  - Creates a new membership object
- [x] increase_member_coins
- [x] decrease_member_coins
- [x] record_member_attendance
  - Creates a new EventAttendance object
- [x] create_event
- [x] create_recurring_event

**Comment by MarcoDelcas** [comment]
## Hi. 
I can help you with the implementation of some functions. I am new to github. I would like to collaborate

**Comment by IkeHunter** [comment]
@MarcoDelcas Sounds good, let me know if you need help with anything. I'll update the CONTRIBUTING.md docs at some point, but the way most ppl contribute is by "forking" the repo to their own account, "cloning" it down to their local machine, making the changes, "pushing" the changes back up to their fork, then creating a "pull request" - or PR. 

Here's a good walkthrough of how to do all of that: <https://github.com/asmeurer/git-workflow>
