### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Club-Manager#25]
## Info

A user should be able to view their information on a the user profile page, including their "badges", club memberships and roles, and personal information. 

Any ideas/suggestions on design or layout are welcomed. If you are comfortable in Django, you can edit the functional view users.views.user_profile_view() to add any necessary context for dynamic data. Otherwise, just mock up a solution using plain html and css, and you can use example data in lieu of dynamic context data (ie using static value "John Doe" instead of {{ user.name }} for a user's name).

## Task

 - [ ] Design page without form to just display personal info
 - [ ] Design page in "edit mode" where user can edit their profile fields (look in the users/models.py > Profile model to see what fields are available)
 - [ ] Build out the profile page

### Files
- Put html in app/users/templates/users/user-profile.html
- Put global CSS in app/static/css/style.css
- Put scoped CSS (specific to that page) in a new file `app/users/static/users/user-profile.css`, add link to `user-profile.html`
- Put JS in `app/static/js/script.js`
- If need scoped JS, create new file: `app/clubs/static/clubs/club-home.js` and add link to `club-home.html`

**Comment by nick1714** [comment]
I'm interesting with your project, can you assign it for me so I can try to fix it!!

**Comment by dev-par** [comment]
Just realized I never commented on this, working on it right now

**Comment by IkeHunter** [comment]
@JonathanHooth, this page might also be helpful when testing with osc members, so we probably want to finish this task too. Also doesn't need to look pretty, just needs to be usable.
