### ISSUE TITLE
Create user on registration

### ISSUE THREAD

**Issue by IkeHunter** [ufosc/Club-Manager#7]
## Info

The html page/form has already been created, this task will involve creating a new user based on their input from the registration form.

When a new user registers, they should now have an account for being able to sign in. Additionally, they should have a page to be able to select from a list of clubs, or optionally create a new club. 

In the future, this feature will be extensively built out to include a paywall for creating a new club, and to be able to handle the user's "membership" with the club (what notifications are sent, what their display name is, what their role is, etc). In the future, this will also probably send admins a notification for approval based on club settings, etc.

However, for now, when a user registers two things should happen:
- Redirect to a club selection page
  - Redirects to a new user profile page
- Create user account

The redirect after the club selection page will later go to a user dashboard of sorts where they might can see an aggregated view of events, clubs, etc; but for now just create a simple profile page that lists user info. It can be ugly, a later issue might cover a full build out of the profile page.

## Task

- [ ] In the registration view, collect the form fields and create a new user using `User.objects.create_user()` function. Throw an error if the user's email already exists in another user's profile (hint: `Profile.objects.filter(email=email).exists()`)
- [ ] On success, redirect user to a club selection page, possibly rendering a new form with a multi select field displaying a list of all clubs
- [ ] When user submits club selection "form", they should be redirected to a page showing their name, email, and clubs (starting point for profile page)

### Optional Challenge

- [ ] Create unit tests for form submission logic

**Comment by IkeHunter** [comment]
@sid0000007 What do you think about taking on this issue? It's a bit more complicated than the last one, but gets you a little deeper into django/python

**Comment by sid0000007** [comment]
> @sid0000007 What do you think about taking on this issue? It's a bit more complicated than the last one, but gets you a little deeper into django/python

I see the task is interesting, you can assign it to me if you want.

**Comment by IkeHunter** [comment]
👍

**Comment by IkeHunter** [comment]
- How to setup virtual envs in vscode: https://code.visualstudio.com/docs/python/environments
- Working with conda: https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html

Once you have the virtual envs, run this in the terminal:

```sh
pip install -r requirements.dev.txt
pip install -r requirements.txt
```

The last command will probably fail with some crazy error talking about psycopg2, you can ignore that. At this point you should be able to have auto import/complete for most of the packages.

**Comment by IkeHunter** [comment]
@sid0000007 I just merged a PR that has the user registration and login stuff worked out if you want to take a look at my solution. This one was pretty difficult tbh, so no worries if you got stuck. I'll be adding some easier issues this week, I'll tag you on some in case you're interested.
